library: ~/audio/beets.db
directory: ~/audio/
art_filename: cover.jpg

import:
    # Do we copy the files when importing?
    copy: false
    # Or do we instead move the music when import?
    move: true
    # Write ID3v2.4 tags to the music?
    write: true
    # Automatically resume from where we left off.
    resume: true

plugins: mpdupdate importfeeds mbcollection lastgenre fetchart replaygain chroma web

paths:
    default: '%asciify{$albumartist}/%asciify{$album%aunique{}}/$track-%asciify{$title}'
    singleton: $artist/non-album/$title
    comp: Compilations/%asciify{$album%aunique{}}/$track-%asciify{$title}

mpdupdate:
    host: localhost
    port: 6600

importfeeds:
    formats: m3u_multi
    dir: ~/audio/playlists/
    m3u_name: beetsimport.m3u

musicbrainz:
    user: evaryont

lastgenre:
    fallback_str: ''

fetchart:
    auto: true

replaygain:
    overwrite: true
