# Rubocop configuration file for NVim and ALE. Neovim will run rubocop against
# any ruby buffer, so these are the editor-specific global defaults.
# 
# Various cops are tweaked to be less annoying, or outright disabled. I don't
# expect that all ruby code I submit publicly will only be checked against this
# config. Indeed, specific projects might already include their own
# configuration as part of the CI pipeline. So this primarily meant to make a
# better editing experience.

Layout/ExtraSpacing:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

# TODO: get vim to highlight trailing spaces instead
Layout/TrailingWhitespace:
  Enabled: true

# Bump up the line count limit for methods. Some of my scripts are just not
# great, so really only warn on VERY long methods.
Metrics/MethodLength:
  Max: 25
